
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/portfolio
    username: portfolio
    password: password
  mail:
    default-encoding: UTF-8
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: yossshhhi@gmail.com
    password: erqh ncdw kyke xcnr
    properties: 
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
debug: true
app:
  base-url: http://localhost:8080
security:
  tokenValidityThreshold: 3
  tokenLifeTimeSeconds: 60
  uploadDirectory: "uploads"

