spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/portfolio
#    username: portfolio
#    password: password
    username: ${psql.user}
    password: ${psql.password}

  h2:
    console:
      enabled: true
  mail:
    default-encoding: UTF-8
    protocol: smtp
#    host: smtp.gmail.com
#    port: 587
#    username: yossshhhi@gmail.com
#    password: erqh ncdw kyke xcnr
    host: ${spring.mail.host}
    port: ${spring.mail.port}
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    properties: 
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
#  base-url: https://saibaitecho.mydns.jp/app
  base-url: ${app.url}
security:
  tokenValidityThreshold: 4
  tokenLifeTimeSeconds: 3600
  
upload:
#  path: "/var/lib/tomcat/webapps/app/WEB-INF/classes/static/images/uploads/"
  path: ${upload.path}
set:
 path : ${set.path}
            