spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/portfolio
    username: ${psql.user}
    password: ${psql.password}
  mail:
    default-encoding: UTF-8
    protocol: smtp
    host: ${spring.mail.host}
    port: ${spring.mail.port}
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    properties: 
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  base-url: http://localhost:8080
security:
  tokenValidityThreshold: 3
  tokenLifeTimeSeconds: 60
  uploadDirectory: "uploads"
            